import { MoveData, CharacterInfo } from "../charInterface.js";

const moMoveset: MoveData[] = [
  // normals
  {
    name: "Standing LP",
    command: "5LP",
    startup: "5",
    active: "3",
    recovery: "8",
    onHit: "5",
    onBlock: "4",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://wiki.gbl.gg/images/f/f9/Vsav-FE-5-lp-hitbox.png",
  },
  {
    name: "Standing MP",
    command: "5MP",
    startup: "5",
    active: "3",
    recovery: "18",
    onHit: "0",
    onBlock: "1",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/5/5e/Vsav-FE-5-mp-hitbox.png",
  },
  {
    name: "Standing HP",
    command: "5HP",
    startup: "7",
    active: "2(4)3,2",
    recovery: "22",
    onHit: "3",
    onBlock: "2",
    cancel: "no",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/b/be/Vsav-FE-5-hp-1-hitbox.png",
  },
  {
    name: "Standing LK",
    command: "5LP",
    startup: "5",
    active: "4",
    recovery: "7",
    onHit: "5",
    onBlock: "4",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/a/a4/Vsav-FE-5-lk-hitbox.png"
  },
  {
    name: "Standing MK",
    command: "5Mk",
    startup: "7",
    active: "3",
    recovery: "19",
    onHit: "2",
    onBlock: "1",
    cancel: "no",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/1/13/Vsav-FE-5-mk-hitbox.png",
  },
  {
    name: "Standing HK",
    command: "5HK",
    startup: "8",
    active: "3(4)3",
    recovery: "24",
    onHit: "-2",
    onBlock: "-3",
    cancel: "no",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/2/2a/Vsav-FE-5-hk-2-hitbox.png",
  },
  // close normals
  {
    name: "Close LP",
    command: "cl.5LP",
    startup: "5",
    active: "3",
    recovery: "7",
    onHit: "9",
    onBlock: "8",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/a/af/Vsav-FE-cl-lp-hitbox.png",
  },
  {
    name: "Close MP",
    command: "cl.5MP",
    startup: "7",
    active: "3",
    recovery: "15",
    onHit: "3",
    onBlock: "2",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/c/cd/Vsav-FE-cl-mp-hitbox.png",
  },
  {
    name: "Close HP",
    command: "cl.5HP",
    startup: "9",
    active: "3,6",
    recovery: "24",
    onHit: "-5",
    onBlock: "-4",
    cancel: "no",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/b/bb/Vsav-FE-cl-hp-3-hitbox.png",
  },
  {
    name: "Close LK",
    command: "cl.5LK",
    startup: "5",
    active: "3",
    recovery: "8",
    onHit: "4",
    onBlock: "5",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/5/54/Vsav-FE-cl-lk-hitbox.png",
  },
  {
    name: "Close MK",
    command: "cl.5MK",
    startup: "6",
    active: "3",
    recovery: "16",
    onHit: "2",
    onBlock: "1",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/0/0b/Vsav-FE-cl-mk-hitbox.png",
  },
  {
    name: "Close HK",
    command: "cl.5HK",
    startup: "7",
    active: "5",
    recovery: "12",
    onHit: "25",
    onBlock: "12",
    cancel: "no",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/1/1a/Vsav-FE-cl-hk-hitbox.png",
  },
  // crouch normals
  {
    name: "Crouch LP",
    command: "2LP",
    startup: "5",
    active: "3",
    recovery: "6",
    onHit: "3",
    onBlock: "6",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/6/6e/Vsav-FE-2-lp-hitbox.png"
  },
  {
    name: "Crouch MP",
    command: "2MP",
    startup: "5",
    active: "4",
    recovery: "14",
    onHit: "3",
    onBlock: "2",
    cancel: "yes",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/1/1d/Vsav-FE-2-mp-hitbox.png",
  },
  {
    name: "Crouch HP",
    command: "2HP",
    startup: "8",
    active: "6",
    recovery: "12",
    onHit: "19",
    onBlock: "6",
    cancel: "no",
    invul: "—",
    guard: "Mid",
    description: "** **",
    image: "https://mizuumi.wiki/images/5/5e/Vsav-FE-2-hp-hitbox.png",
  },
  {
    name: "Crouch LK",
    command: "2LK",
    startup: "5",
    active: "3",
    recovery: "7",
    onHit: "6",
    onBlock: "5",
    cancel: "yes",
    invul: "—",
    guard: "Low",
    description: "** **",
  image:"https://mizuumi.wiki/images/4/43/Vsav-FE-2-lk-hitbox.png",
  },
  {
    name: "Crouch MK",
    command: "2MK",
    startup: "6",
    active: "3",
    recovery: "18",
    onHit: "0",
    onBlock: "1",
    cancel: "yes",
    invul: "—",
    guard: "Low",
    description: "** **",
    image: "https://mizuumi.wiki/images/c/cb/Vsav-FE-2-mk-hitbox.png",
  },
  {
    name: "Crouch HK",
    command: "2HK",
    startup: "8",
    active: "2",
    recovery: "21",
    onHit: "—",
    onBlock: "3",
    cancel: "no",
    invul: "—",
    guard: "Low",
    description: "** **",
    image: "https://mizuumi.wiki/images/7/72/Vsav-FE-2-hk-hitbox.png",
  }
  // jumping normals
  // especial moves
  // ex moves
  // throws
  // guard cancel
  // pursuit
  // dark force
];

export const felicia: CharacterInfo = {
  name: "Felicia",
  icon: "https://mizuumi.wiki/images/thumb/b/ba/Vsav-nav-portrait-felicia.gif/105px-Vsav-nav-portrait-felicia.gif",
  moves: moMoveset,
};
